create or replace TRIGGER FDT_TRB_FDTUOC_BIR
BEFORE INSERT ON FDTT_UNITE_ORGAN_CORRE
FOR EACH ROW
BEGIN
   IF :NEW.NO_SEQ_UNITE_ORGAN_CORRE IS NULL THEN
      SELECT FDTUCOR_SEQ.nextval 
	    INTO :NEW.NO_SEQ_UNITE_ORGAN_CORRE        
      FROM DUAL;
   END IF;
END;
/
show errors
